version: "3"


services:

  mystore_frontend:
    build:
      context: ./mystore_frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - mystore_ms
    ports:
      - "8085:80"

  mystore_ms:
    build:
      context: ./bigstore_ms
      dockerfile: Dockerfile
    restart: always
    depends_on:
       - bigstoredb
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      URL : ${URL}
    ports:
      - "4000:4000"    

  bigstoredb:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pg123
    ports:
      - "5050:80"
